---
- name: Get Device Facts
  hosts: vsrx2
  roles:
  - Juniper.junos
  connection: local
  gather_facts: no

  tasks:
  - name: Checking NETCONF connectivity
    wait_for: host={{ ansible_ssh_host }} port=830 timeout=5

  - name: Retrieve information from devices running Junos OS
    junos_get_facts:
       host={{ ansible_ssh_host }}
       user={{ junos_user }}
       passwd={{ junos_password }}
       savedir=/tmp
    register: junos
  
  - name: Show all
    debug: msg="{{ junos.facts }}"

  - name: version
    debug: msg="{{ junos.facts.version, junos.facts.model }}"

  - name: Execute CLI
    junos_cli:
       host: "{{ ansible_ssh_host }}"
       user: "{{ junos_user }}"
       passwd: "{{ junos_password }}"
       cli: "show chassis hardware"
       logfile: cli.log
       dest: "{{ inventory_hostname }}.xml"
       format: xml

