---
- name: Get Device Hardware
  hosts: vsrx2
  roles:
  - Juniper.junos
  connection: local
  gather_facts: no

  tasks:
  - name: Checking NETCONF connectivity
    wait_for: host={{ inventory_hostname }} port=830 timeout=5

  - name: Execute CLI
    junos_cli:
       host: "{{ inventory_hostname }}"
       user: "{{ junos_user }}"
       passwd: "{{ junos_password }}"
       cli: "show chassis hardware"
       logfile: cli.log
       dest: "{{ inventory_hostname }}.xml"
       format: xml

